name: Storage Integration Service
on:
  pull_request:
    paths:
      - 'delta/kernel/**'
      - 'delta/rdf/**'
      - 'storage/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/ci-storage.yml'
jobs:
  review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: StaticAnalysis
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project storage" clean scalafmtCheck Test/scalafmtCheck scalafmtSbtCheck scapegoat
      - name: Tests
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project storage" clean coverage test coverageReport coverageAggregate
      - name: Assembly
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project storage" assembly
